const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');const storage=require('./db');
const PORT=process.env.PORT||3000,PUBLIC=path.join(__dirname,'public');
const IS_PROD=process.env.NODE_ENV==='production';const MAX_BODY=Number(process.env.MAX_BODY_BYTES||100000);
const CORS_ORIGIN=process.env.CORS_ORIGIN||'http://localhost:'+PORT;const RATE=new Map();
function rateLimit(key,limit=60,windowMs=60000){const t=Date.now(),a=RATE.get(key)||[];const fresh=a.filter(x=>x>t-windowMs);fresh.push(t);RATE.set(key,fresh);return fresh.length<=limit}
function clientKey(req){return(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim()}
function secureHeaders(res){res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(),microphone=(),geolocation=()');if(IS_PROD)res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains')}
const APP_VERSION='0.16.0';
const defaults={businessName:'Demo Business',responseTone:'professional',services:'Website design, digital marketing',prices:'',faq:'We respond during business hours.',hours:'Monday–Friday, 9:00–17:00',contactInfo:'',followupHours:24,maxFollowups:3,notificationEmail:'',aiProvider:process.env.OPENAI_API_KEY?'openai':'demo',webhookUrl:'',webhookSecret:'',webhookEnabled:false,emailEnabled:false,emailFrom:process.env.EMAIL_FROM||'',resendApiKey:process.env.RESEND_API_KEY||''};
function now(){return new Date().toISOString()}function id(){return crypto.randomUUID()}function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){return{salt,hash:crypto.scryptSync(password,salt,64).toString('hex')}}function verifyPassword(password,r){try{return crypto.timingSafeEqual(Buffer.from(hashPassword(password,r.salt).hash,'hex'),Buffer.from(r.hash,'hex'))}catch{return false}}function token(){return crypto.randomBytes(32).toString('hex')}function apiKey(){return'alr_'+crypto.randomBytes(24).toString('hex')}function intakeToken(){return'int_'+crypto.randomBytes(24).toString('hex')}
function load(){const db=storage.get();seed(db);return db}function save(db){storage.save(db)}
function seed(db){if(!db.workspaces.length){const wid=id();db.workspaces.push({id:wid,name:db.settings?.businessName||'Demo Workspace',createdAt:now(),apiKey:apiKey(),intakeToken:intakeToken()});db.leads.forEach(l=>l.workspaceId=wid);db.settingsByWorkspace[wid]={...defaults,...(db.settings||{}),workspaceId:wid}}else for(const w of db.workspaces){if(!w.apiKey)w.apiKey=apiKey();if(!w.intakeToken)w.intakeToken=intakeToken();if(!db.settingsByWorkspace[w.id])db.settingsByWorkspace[w.id]={...defaults,...(db.settings||{}),workspaceId:w.id}}}
function getSettings(db,wid){return db.settingsByWorkspace[wid]||{...defaults,workspaceId:wid}}function getSession(req,db){const c=req.headers.cookie||'',m=c.match(/(?:^|; )alr_session=([^;]+)/);if(!m)return null;const s=db.sessions.find(x=>x.token===m[1]&&x.expiresAt>Date.now());if(!s)return null;const u=db.users.find(x=>x.id===s.userId);return u?{...s,user:u}:null}function authRequired(){return IS_PROD||process.env.AUTH_REQUIRED==='true'}
function workspaceFrom(req,db){const ss=getSession(req,db);if(ss)return{workspaceId:ss.user.workspaceId,user:ss.user,session:ss};const key=req.headers['x-api-key'];if(key){const w=db.workspaces.find(x=>x.apiKey===key);if(w)return{workspaceId:w.id,user:null,workspace:w}}return null}
function json(res,status,b){secureHeaders(res);res.writeHead(status,{'Content-Type':'application/json','Access-Control-Allow-Origin':CORS_ORIGIN,'Access-Control-Allow-Methods':'GET,POST,PATCH,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-API-Key,X-Intake-Token','Vary':'Origin'});res.end(JSON.stringify(b))}
function read(req){return new Promise((ok,bad)=>{let d='',n=0;req.on('data',c=>{n+=c.length;if(n>MAX_BODY){req.destroy();return bad(new Error('Request body too large'))}d+=c});req.on('end',()=>{try{ok(d?JSON.parse(d):{})}catch{bad(new Error('Invalid JSON'))}})})}
function setCookie(res,t){res.setHeader('Set-Cookie',`alr_session=${t}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${IS_PROD?'; Secure':''}`)}function clearCookie(res){res.setHeader('Set-Cookie','alr_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0')}
function isOptOut(message){return/\b(stop|unsubscribe|remove me|do not contact|don't contact|no more emails)\b/i.test(message||'')}
function followupAllowed(lead,s){return!lead.paused&&!lead.optedOut&&lead.followupCount<Number(s.maxFollowups||3)&&!['Engaged','Human Required','Won','Lost'].includes(lead.status)}
function analyze(message){const m=(message||'').toLowerCase();const urgent=/(today|tomorrow|urgent|asap|this week|next week|deadline|within\s+(?:the\s+next\s+)?(\d+|one|two|three|four|five|six|seven|eight|nine|ten)\s+(day|days|week|weeks))/.test(m);const intent=/(website|web|site)/.test(m)?'Website design':/(marketing|ads|advertising|seo)/.test(m)?'Marketing':/(recruit|job|hire|staff)/.test(m)?'Recruitment':/(price|cost|quote|how much)/.test(m)?'Pricing inquiry':'General inquiry';const human=/(refund|complaint|legal|contract|discount|cancel|angry|speak to\s+(a\s+)?human|manager)/.test(m);const temp=human?'Human Required':(urgent||/(buy|book|hire|ready|interested|quote)/.test(m)?'Hot':/(maybe|consider|thinking|information)/.test(m)?'Warm':'Cold');return{intent,temperature:temp,urgency:urgent?'High':'Normal',summary:`${intent} inquiry${urgent?' with a time-sensitive requirement':''}.`,aiConfidence:human?.84:.91,needsHuman:human}}
async function aiResponse(lead,s){if(s.aiProvider==='openai'&&process.env.OPENAI_API_KEY){try{const prompt=`You are the lead-response assistant for ${s.businessName}. Use ONLY this business information. Services: ${s.services}. Prices: ${s.prices||'Not provided'}. FAQ: ${s.faq}. Hours: ${s.hours}. Contact: ${s.contactInfo||'Not provided'}. Never invent facts. If information is missing, say a team member will confirm. Keep concise. Customer: ${lead.name||'there'}. Message: ${lead.originalMessage}`;const r=await fetch(process.env.OPENAI_BASE_URL||'https://api.openai.com/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-4o-mini',messages:[{role:'system',content:prompt}],temperature:.2})});if(r.ok){const j=await r.json();return j.choices?.[0]?.message?.content?.trim()||null}}catch(e){console.error('AI provider error',e.message)}}return null}
function demoResponse(l,s){const g=l.name?`Hi ${l.name},`:'Hi there,';if(l.needsHuman)return`${g}\n\nThanks for reaching out. I’ve flagged this for a team member so we can give you an accurate answer without guessing.\n\nBest,\n${s.businessName}`;return`${g}\n\nThanks for your interest in ${s.businessName}. We received your ${l.intent.toLowerCase()} inquiry. ${s.prices?'We can confirm the relevant pricing from our current information.':'A team member will confirm the specific pricing/details for you.'} If you can share your preferred timeline and the best contact method, we can move this forward faster.\n\nBest,\n${s.businessName}`}
async function makeResponse(l,s){return(await aiResponse(l,s))||demoResponse(l,s)}
function event(db,type,leadId,workspaceId,extra={}){const e={id:id(),type,leadId,workspaceId,at:now(),...extra};db.events.unshift(e);db.events=db.events.slice(0,1000);return e}
async function deliverWebhook(db,e,s){if(!s.webhookEnabled||!s.webhookUrl)return{sent:false,reason:'disabled'};const body=JSON.stringify({event:e.type,eventId:e.id,timestamp:e.at,leadId:e.leadId,data:e});const signature=crypto.createHmac('sha256',s.webhookSecret||'').update(body).digest('hex');let last='';for(let i=1;i<=3;i++){try{const r=await fetch(s.webhookUrl,{method:'POST',headers:{'content-type':'application/json','x-ai-lead-rescue-signature':signature,'x-ai-lead-rescue-event':e.type,'x-ai-lead-rescue-attempt':String(i)},body});if(r.ok)return{sent:true,status:r.status,attempt:i};last=`HTTP ${r.status}`}catch(err){last=err.message}if(i<3)await new Promise(r=>setTimeout(r,250*i))}return{sent:false,error:last}}
async function emit(db,type,lead,extra={}){const e=event(db,type,lead?.id||null,lead?.workspaceId,extra);save(db);const s=getSettings(db,lead?.workspaceId);const d=await deliverWebhook(db,e,s);if(d.sent)event(db,'webhook.delivered',lead?.id||null,lead?.workspaceId,{sourceEvent:type,attempt:d.attempt});else if(s.webhookEnabled&&s.webhookUrl)event(db,'webhook.failed',lead?.id||null,lead?.workspaceId,{sourceEvent:type,error:d.error||d.reason});save(db);return e}
async function sendEmail(to,subject,text,s){if(!s.emailEnabled||!s.resendApiKey||!s.emailFrom||!to)return{sent:false,reason:'email_not_configured'};try{const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{'content-type':'application/json','Authorization':`Bearer ${s.resendApiKey}`},body:JSON.stringify({from:s.emailFrom,to:[to],subject,text})});if(r.ok)return{sent:true};return{sent:false,error:`HTTP ${r.status}`}}catch(e){return{sent:false,error:e.message}}}
async function safeNotify(s,lead,message){const to=s.notificationEmail;if(!to||!s.emailEnabled||!s.resendApiKey||!s.emailFrom)return false;const r=await sendEmail(to,`Lead reply: ${lead.name||lead.email||lead.id}`,`A customer replied to ${s.businessName}.\n\nLead: ${lead.name||''} <${lead.email||''}>\nMessage: ${message}\n\nStatus: ${lead.status}`,s);return!!r.sent}
async function createLead(db,x,wid){const t=now(),s=getSettings(db,wid),a=analyze(x.originalMessage||x.message||'');const lead={id:id(),workspaceId:wid,name:x.name||'',email:x.email||'',phone:x.phone||'',company:x.company||'',source:x.source||'Webhook',originalMessage:x.originalMessage||x.message||'',...a,status:a.needsHuman?'Human Required':'New',assignedPerson:'',lastContact:null,nextFollowup:null,followupCount:0,createdDate:t,updatedDate:t,response:'',conversation:[{role:'customer',message:x.originalMessage||x.message||'',at:t}],idempotencyKey:x.idempotencyKey||x._idempotencyKey||null,paused:false,optedOut:false};lead.response=await makeResponse(lead,s);db.leads.unshift(lead);await emit(db,'lead.created',lead,{source:lead.source});await emit(db,'lead.analyzed',lead);if(lead.email&&!lead.needsHuman){lead.status='Contacted';lead.lastContact=now();lead.nextFollowup=new Date(Date.now()+Number(s.followupHours||24)*3600000).toISOString();lead.conversation.push({role:'assistant',message:lead.response,at:lead.lastContact});const mail=await sendEmail(lead.email,`Re: ${lead.intent} — ${s.businessName}`,lead.response,s);await emit(db,'lead.responded',lead,{emailDelivery:mail,automatic:true})}save(db);return lead}
async function route(req,res){if(req.method==='OPTIONS')return json(res,204,{});const url=new URL(req.url,`http://${req.headers.host}`),db=load();
if(req.method==='POST'&&url.pathname==='/api/auth/register'){if(!rateLimit('reg:'+clientKey(req),8,3600000))return json(res,429,{error:'Too many registration attempts. Try again later.'});const x=await read(req),email=String(x.email||'').trim().toLowerCase(),password=String(x.password||'');if(!email||password.length<8)return json(res,400,{error:'Email and password (8+ characters) are required'});if(db.users.some(u=>u.email===email))return json(res,409,{error:'Account already exists'});const wid=id(),uid=id(),pw=hashPassword(password),key=apiKey();db.workspaces.push({id:wid,name:x.businessName||email.split('@')[0],createdAt:now(),apiKey:key,intakeToken:intakeToken()});db.settingsByWorkspace[wid]={...defaults,businessName:x.businessName||email.split('@')[0],workspaceId:wid};db.users.push({id:uid,email,workspaceId:wid,password:pw,createdAt:now()});const t=token();db.sessions.push({token:t,userId:uid,expiresAt:Date.now()+604800000});save(db);setCookie(res,t);return json(res,201,{ok:true,user:{id:uid,email,workspaceId:wid},apiKey:key})}
if(req.method==='POST'&&url.pathname==='/api/auth/login'){if(!rateLimit('login:'+clientKey(req),15,900000))return json(res,429,{error:'Too many login attempts. Try again later.'});const x=await read(req),email=String(x.email||'').trim().toLowerCase(),u=db.users.find(v=>v.email===email);if(!u||!verifyPassword(String(x.password||''),u.password))return json(res,401,{error:'Invalid email or password'});const t=token();db.sessions=db.sessions.filter(s=>s.expiresAt>Date.now());db.sessions.push({token:t,userId:u.id,expiresAt:Date.now()+604800000});save(db);setCookie(res,t);return json(res,200,{ok:true,user:{id:u.id,email:u.email,workspaceId:u.workspaceId},apiKey:db.workspaces.find(w=>w.id===u.workspaceId)?.apiKey})}
if(req.method==='POST'&&url.pathname==='/api/auth/logout'){const ss=getSession(req,db);if(ss)db.sessions=db.sessions.filter(s=>s.token!==ss.token);save(db);clearCookie(res);return json(res,200,{ok:true})}
if(req.method==='GET'&&url.pathname==='/api/auth/me'){const ss=getSession(req,db);return json(res,200,{authenticated:!!ss,user:ss?{id:ss.user.id,email:ss.user.email,workspaceId:ss.user.workspaceId}:null,required:authRequired()})}
if(req.method==='POST'&&url.pathname==='/api/public/leads'){if(!rateLimit('intake:'+clientKey(req),30,60000))return json(res,429,{error:'Too many enquiries. Please try again shortly.'});const tok=req.headers['x-intake-token'];const w=db.workspaces.find(x=>x.intakeToken===tok);if(!w)return json(res,401,{error:'Invalid intake token'});try{const x=await read(req);if(!x.originalMessage&&!x.message)return json(res,400,{error:'Message is required'});const idem=String(req.headers['idempotency-key']||x.idempotencyKey||'').trim();if(idem){const prior=db.leads.find(l=>l.workspaceId===w.id&&l.idempotencyKey===idem);if(prior)return json(res,200,{ok:true,duplicate:true,leadId:prior.id,status:prior.status})}if(idem)x.idempotencyKey=idem;const lead=await createLead(db,x,w.id);return json(res,201,{ok:true,leadId:lead.id,status:lead.status,emailAttempted:Boolean(lead.email&&getSettings(db,w.id).emailEnabled&&getSettings(db,w.id).resendApiKey&&getSettings(db,w.id).emailFrom)})}catch(e){return json(res,400,{error:e.message})}}
if(req.method==='POST'&&url.pathname==='/api/public/reply'){const tok=req.headers['x-intake-token'];const w=db.workspaces.find(x=>x.intakeToken===tok);if(!w)return json(res,401,{error:'Invalid intake token'});try{const x=await read(req),msg=String(x.message||'').trim();if(!msg)return json(res,400,{error:'Message is required'});let lead=x.leadId?db.leads.find(l=>l.id===x.leadId&&l.workspaceId===w.id):db.leads.find(l=>l.workspaceId===w.id&&x.email&&l.email===String(x.email).toLowerCase()&&!['Won','Lost'].includes(l.status));if(!lead)return json(res,404,{error:'Lead not found'});lead.lastInboundMessage=msg;lead.conversation=lead.conversation||[];lead.conversation.push({role:'customer',message:msg,at:now()});lead.optedOut=isOptOut(msg);lead.status=lead.optedOut?'Nurture':'Engaged';lead.nextFollowup=null;lead.updatedDate=now();await emit(db,'lead.replied',lead,{channel:x.channel||'inbound',optedOut:lead.optedOut});await safeNotify(getSettings(db,w.id),lead,msg);save(db);return json(res,200,{ok:true,leadId:lead.id,status:lead.status,automationStopped:true,optedOut:!!lead.optedOut})}catch(e){return json(res,400,{error:e.message})}}
if(req.method==='GET'&&url.pathname==='/api/health'){const ds=await storage.status();return json(res,200,{ok:true,service:'ai-lead-rescue',version:APP_VERSION,environment:IS_PROD?'production':'development',database:ds.type,databaseOk:ds.ok,time:now()})}
if(req.method==='GET'&&url.pathname==='/api/ready'){const ds=await storage.status();return json(res,ds.ok?200:503,{ready:ds.ok,version:APP_VERSION,database:ds.type,time:now(),error:ds.ok?undefined:ds.error})}
if(req.method==='GET'&&url.pathname==='/sales'){const html=fs.readFileSync(path.join(__dirname,'public','sales.html'),'utf8');res.writeHead(200,{'content-type':'text/html; charset=utf-8'});return res.end(html)}
if(req.method==='GET'&&url.pathname==='/api/integration-guide')return json(res,200,{version:APP_VERSION,endpoints:{intake:'POST /api/public/leads',reply:'POST /api/public/reply',export:'GET /api/leads.csv',leads:'GET /api/leads',webhookTest:'POST /api/test-webhook'},headers:{intake:'X-Intake-Token',api:'X-API-Key',idempotency:'Idempotency-Key'},events:['lead.created','lead.analyzed','lead.responded','followup.due','lead.replied','human.handoff','lead.closed','lead.updated','webhook.delivered','webhook.failed']});
let ctx=workspaceFrom(req,db);if(authRequired()&&!ctx)return json(res,401,{error:'Authentication required'});if(!ctx){const wid=db.workspaces[0]?.id;ctx={workspaceId:wid,user:null}}
const wid=ctx.workspaceId,s=getSettings(db,wid);
if(req.method==='GET'&&url.pathname==='/api/leads'){let ls=db.leads.filter(l=>l.workspaceId===wid);const q=(url.searchParams.get('q')||'').toLowerCase(),status=url.searchParams.get('status'),temp=url.searchParams.get('temperature');if(q)ls=ls.filter(l=>[l.name,l.email,l.company,l.originalMessage,l.intent].join(' ').toLowerCase().includes(q));if(status)ls=ls.filter(l=>l.status===status);if(temp)ls=ls.filter(l=>l.temperature===temp);return json(res,200,ls)}
if(req.method==='GET'&&url.pathname==='/api/leads.csv'){const ls=db.leads.filter(l=>l.workspaceId===wid),esc=v=>`"${String(v??'').replace(/"/g,'""').replace(/\r?\n/g,' ')}"`,header=['id','name','email','phone','company','source','intent','temperature','urgency','status','followupCount','createdDate','updatedDate'],csv=[header.join(','),...ls.map(l=>header.map(k=>esc(l[k])).join(','))].join('\n');secureHeaders(res);res.writeHead(200,{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename=ai-lead-rescue-leads.csv','Access-Control-Allow-Origin':CORS_ORIGIN});return res.end(csv)}
if(req.method==='GET'&&url.pathname==='/api/events')return json(res,200,db.events.filter(e=>e.workspaceId===wid).slice(0,100));
if(req.method==='GET'&&url.pathname==='/api/settings')return json(res,200,{...s,resendApiKey:s.resendApiKey?'••••••••':'',webhookSecretMasked:s.webhookSecret?'••••••••':'',intakeToken:db.workspaces.find(w=>w.id===wid)?.intakeToken||''});
if(req.method==='POST'&&url.pathname==='/api/leads'){try{return json(res,201,{lead:await createLead(db,await read(req),wid),event:'lead.created'})}catch(e){return json(res,400,{error:e.message})}}
if(req.method==='POST'&&url.pathname==='/api/leads/bulk'){try{const x=await read(req),arr=Array.isArray(x.leads)?x.leads:[],out=[];for(const item of arr)out.push(await createLead(db,item,wid));return json(res,201,{count:out.length,leads:out})}catch(e){return json(res,400,{error:e.message})}}
const m=url.pathname.match(/^\/api\/leads\/([^/]+)(?:\/(analyze|respond|follow-up|handoff|reply|close))?$/);if(m){const lead=db.leads.find(l=>l.id===m[1]&&l.workspaceId===wid);if(!lead)return json(res,404,{error:'Lead not found'});const action=m[2];
if(req.method==='PATCH'&&!action){Object.assign(lead,await read(req),{updatedDate:now()});await emit(db,'lead.updated',lead);return json(res,200,{lead})}
if(req.method==='POST'&&action==='analyze'){Object.assign(lead,analyze(lead.originalMessage),{updatedDate:now()});lead.response=await makeResponse(lead,s);await emit(db,'lead.analyzed',lead);return json(res,200,{lead})}
if(req.method==='POST'&&action==='respond'){lead.response=await makeResponse(lead,s);lead.status=lead.status==='New'?'Contacted':lead.status;lead.lastContact=now();lead.nextFollowup=new Date(Date.now()+Number(s.followupHours||24)*3600000).toISOString();lead.updatedDate=now();lead.conversation.push({role:'assistant',message:lead.response,at:lead.lastContact});const mail=await sendEmail(lead.email,`Re: ${lead.intent} — ${s.businessName}`,lead.response,s);await emit(db,'lead.responded',lead,{emailDelivery:mail});return json(res,200,{lead,emailDelivery:mail})}
if(req.method==='POST'&&action==='follow-up'){if(!followupAllowed(lead,s))return json(res,409,{error:'Follow-up is paused, opted out, complete, or the maximum follow-up count has been reached',lead});lead.followupCount++;lead.status=lead.status==='New'?'Contacted':lead.status;lead.lastContact=now();lead.nextFollowup=new Date(Date.now()+Number(s.followupHours||24)*3600000).toISOString();lead.updatedDate=now();const mail=await sendEmail(lead.email,`Following up — ${s.businessName}`,lead.response||'Just following up on your inquiry. A team member is available to help.',s);await emit(db,'followup.due',lead,{emailDelivery:mail});return json(res,200,{lead,emailDelivery:mail})}
if(req.method==='POST'&&action==='handoff'){lead.status='Human Required';lead.nextFollowup=null;lead.updatedDate=now();await emit(db,'human.handoff',lead);await safeNotify(s,lead,'Human handoff requested for this lead.');return json(res,200,{lead})}
if(req.method==='POST'&&action==='reply'){const x=await read(req),msg=String(x.message||'');lead.lastInboundMessage=msg;lead.conversation.push({role:'customer',message:msg,at:now()});lead.optedOut=isOptOut(msg);lead.status=lead.optedOut?'Nurture':'Engaged';lead.nextFollowup=null;lead.updatedDate=now();await emit(db,'lead.replied',lead,{optedOut:lead.optedOut});await safeNotify(s,lead,msg);return json(res,200,{lead})}
if(req.method==='POST'&&action==='close'){const x=await read(req);lead.status=x.status||'Won';lead.nextFollowup=null;lead.updatedDate=now();await emit(db,'lead.closed',lead,{outcome:lead.status});return json(res,200,{lead})}}
if(req.method==='POST'&&/^\/api\/leads\/[^/]+\/pause$/.test(url.pathname)){const lid=url.pathname.split('/')[3],lead=db.leads.find(l=>l.id===lid&&l.workspaceId===wid);if(!lead)return json(res,404,{error:'Lead not found'});lead.paused=!lead.paused;lead.nextFollowup=lead.paused?null:new Date(Date.now()+Number(s.followupHours||24)*3600000).toISOString();lead.updatedDate=now();await emit(db,'lead.updated',lead,{paused:lead.paused});return json(res,200,{lead})}
if(req.method==='POST'&&url.pathname==='/api/settings'){if(req.headers['content-type']&&!req.headers['content-type'].includes('application/json'))return json(res,415,{error:'Content-Type must be application/json'});if(!ctx.user&&authRequired())return json(res,403,{error:'Login required'});const x=await read(req);delete x.webhookSecretMasked;delete x.resendApiKey;const next={...s,...x};if(next.webhookEnabled&&!next.webhookSecret)next.webhookSecret=crypto.randomBytes(24).toString('hex');if(process.env.RESEND_API_KEY)next.resendApiKey=process.env.RESEND_API_KEY;db.settingsByWorkspace[wid]=next;save(db);return json(res,200,{...next,resendApiKey:next.resendApiKey?'••••••••':'',webhookSecretMasked:next.webhookSecret?'••••••••':'',intakeToken:db.workspaces.find(w=>w.id===wid)?.intakeToken||''})}
if(req.method==='POST'&&url.pathname==='/api/test-webhook'){const e={id:id(),type:'webhook.test',leadId:null,workspaceId:wid,at:now(),message:'AI Lead Rescue webhook test'},d=await deliverWebhook(db,e,s);return json(res,200,{ok:d.sent,delivery:d,event:e})}
if(req.method==='POST'&&url.pathname==='/api/rotate-intake-token'){if(!ctx.user)return json(res,403,{error:'Login required'});const w=db.workspaces.find(w=>w.id===wid);w.intakeToken=intakeToken();save(db);return json(res,200,{intakeToken:w.intakeToken})}
if(req.method==='POST'&&url.pathname==='/api/rotate-api-key'){if(!ctx.user)return json(res,403,{error:'Login required'});const w=db.workspaces.find(w=>w.id===wid);w.apiKey=apiKey();save(db);return json(res,200,{apiKey:w.apiKey})}
if(req.method==='GET'){let p=url.pathname==='/'?'/index.html':url.pathname;const file=path.join(PUBLIC,p.replace(/^\//,''));if(file.startsWith(PUBLIC)&&fs.existsSync(file)&&fs.statSync(file).isFile()){const ext=path.extname(file),types={'.html':'text/html','.js':'text/javascript','.css':'text/css'};secureHeaders(res);res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':IS_PROD?'public, max-age=300':'no-store'});return fs.createReadStream(file).pipe(res)}}return json(res,404,{error:'Not found'})}
const server=http.createServer((req,res)=>route(req,res).catch(e=>{console.error(e);json(res,500,{error:'Server error'})}));
storage.init().then(()=>server.listen(PORT,()=>console.log(`AI Lead Rescue v${APP_VERSION} on http://localhost:${PORT}`))).catch(e=>{console.error('Storage initialization failed',e);process.exit(1)});
process.on('SIGTERM',async()=>{await storage.close();server.close(()=>process.exit(0))});process.on('SIGINT',async()=>{await storage.close();server.close(()=>process.exit(0))});
setInterval(async()=>{try{const db=load(),cut=Date.now();for(const lead of db.leads.filter(l=>l.nextFollowup&&new Date(l.nextFollowup).getTime()<=cut&&followupAllowed(l,getSettings(db,l.workspaceId)))){const s=getSettings(db,lead.workspaceId);lead.followupCount++;lead.lastContact=now();lead.nextFollowup=lead.followupCount<Number(s.maxFollowups||3)?new Date(Date.now()+Number(s.followupHours||24)*3600000).toISOString():null;const mail=await sendEmail(lead.email,`Following up — ${s.businessName}`,lead.response||'Just following up on your inquiry. A team member is available to help.',s);await emit(db,'followup.due',lead,{automated:true,emailDelivery:mail})}save(db)}catch(e){console.error('follow-up worker',e.message)}},60000);